{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "from bs4 import BeautifulSoup\n",
    "import os, sys, time, resource, re, gc, shutil\n",
    "from multiprocess import Pool\n",
    "from functools import partial\n",
    "from tabulate import tabulate\n",
    "from urllib.parse import urlparse, parse_qsl\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from mongoengine.queryset.visitor import Q\n",
    "import django\n",
    "from django.db.models import Count, Sum\n",
    "sys.path.append('/home/galm/software/django/tmv/BasicBrowser/')\n",
    "os.environ.setdefault(\"DJANGO_SETTINGS_MODULE\", \"BasicBrowser.settings\")\n",
    "django.setup()\n",
    "\n",
    "from django.forms.models import model_to_dict\n",
    "\n",
    "from scoping.models import *\n",
    "from tmv_app.models import *\n",
    "from scipy import stats\n",
    "import ipy_table as tbl\n",
    "from itertools import islice"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.4/dist-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system (\"lxml\"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.\n",
      "\n",
      "The code that caused this warning is on line 170 of the file /usr/lib/python3.4/runpy.py. To get rid of this warning, change code that looks like this:\n",
      "\n",
      " BeautifulSoup(YOUR_MARKUP})\n",
      "\n",
      "to this:\n",
      "\n",
      " BeautifulSoup(YOUR_MARKUP, \"lxml\")\n",
      "\n",
      "  markup_type=markup_type))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "could not find doc with doi: \n",
      "could not find doc with doi: \n",
      "could not find doc with doi: \n",
      "could not find doc with doi: \n",
      "could not find doc with doi: \n",
      "could not find doc with doi: \n",
      "could not find doc with doi: \n",
      "could not find doc with doi: \n",
      "could not find doc with doi: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "could not find doc with doi: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.4/dist-packages/IPython/core/interactiveshell.py\", line 2881, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-3-9fa8f29a68d9>\", line 81, in <module>\n",
      "    ndf[t] = ndf.apply(lambda x: istech(x,t),axis=1)\n",
      "  File \"/usr/local/lib/python3.4/dist-packages/pandas/core/frame.py\", line 4152, in apply\n",
      "    return self._apply_standard(f, axis, reduce=reduce)\n",
      "  File \"/usr/local/lib/python3.4/dist-packages/pandas/core/frame.py\", line 4208, in _apply_standard\n",
      "    labels=labels)\n",
      "  File \"pandas/src/reduce.pyx\", line 623, in pandas.lib.reduce (pandas/lib.c:45030)\n",
      "  File \"pandas/src/reduce.pyx\", line 135, in pandas.lib.Reducer.get_result (pandas/lib.c:34673)\n",
      "  File \"<ipython-input-3-9fa8f29a68d9>\", line 81, in <lambda>\n",
      "    ndf[t] = ndf.apply(lambda x: istech(x,t),axis=1)\n",
      "  File \"<ipython-input-3-9fa8f29a68d9>\", line 73, in istech\n",
      "    relevant=1\n",
      "  File \"/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py\", line 85, in manager_method\n",
      "    return getattr(self.get_queryset(), name)(*args, **kwargs)\n",
      "  File \"/usr/local/lib/python3.4/dist-packages/django/db/models/query.py\", line 796, in filter\n",
      "    return self._filter_or_exclude(False, *args, **kwargs)\n",
      "  File \"/usr/local/lib/python3.4/dist-packages/django/db/models/query.py\", line 814, in _filter_or_exclude\n",
      "    clone.query.add_q(Q(*args, **kwargs))\n",
      "  File \"/usr/local/lib/python3.4/dist-packages/django/db/models/sql/query.py\", line 1227, in add_q\n",
      "    clause, _ = self._add_q(q_object, self.used_aliases)\n",
      "  File \"/usr/local/lib/python3.4/dist-packages/django/db/models/sql/query.py\", line 1253, in _add_q\n",
      "    allow_joins=allow_joins, split_subq=split_subq,\n",
      "  File \"/usr/local/lib/python3.4/dist-packages/django/db/models/sql/query.py\", line 1133, in build_filter\n",
      "    lookups, parts, reffed_expression = self.solve_lookup_type(arg)\n",
      "  File \"/usr/local/lib/python3.4/dist-packages/django/db/models/sql/query.py\", line 1019, in solve_lookup_type\n",
      "    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())\n",
      "  File \"/usr/local/lib/python3.4/dist-packages/django/db/models/sql/query.py\", line 1349, in names_to_path\n",
      "    pathinfos = field.get_path_info()\n",
      "  File \"/usr/local/lib/python3.4/dist-packages/django/db/models/fields/related.py\", line 667, in get_path_info\n",
      "    return [PathInfo(from_opts, opts, self.foreign_related_fields, self, False, True)]\n",
      "  File \"<string>\", line 12, in __new__\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.4/dist-packages/IPython/core/interactiveshell.py\", line 1821, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.4/dist-packages/IPython/core/ultratb.py\", line 1132, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/usr/local/lib/python3.4/dist-packages/IPython/core/ultratb.py\", line 313, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/usr/local/lib/python3.4/dist-packages/IPython/core/ultratb.py\", line 358, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/usr/lib/python3.4/inspect.py\", line 1338, in getinnerframes\n",
      "    framelist.append((tb.tb_frame,) + getframeinfo(tb, context))\n",
      "  File \"/usr/lib/python3.4/inspect.py\", line 1298, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/usr/lib/python3.4/inspect.py\", line 583, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/usr/lib/python3.4/inspect.py\", line 629, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"/usr/lib/python3.4/posixpath.py\", line 372, in realpath\n",
      "    path, ok = _joinrealpath(filename[:0], filename, {})\n",
      "  File \"/usr/lib/python3.4/posixpath.py\", line 406, in _joinrealpath\n",
      "    if not islink(newpath):\n",
      "  File \"/usr/lib/python3.4/posixpath.py\", line 161, in islink\n",
      "    st = os.lstat(path)\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m"
     ]
    }
   ],
   "source": [
    "fnames = [\n",
    "    #'bib_data/1990-2005/pre_2006_2 [Nodes].csv',\n",
    "    'bib_data/1990-2017/all_years [Nodes].csv',\n",
    "]\n",
    "\n",
    "for fname in fnames:\n",
    "\n",
    "    df = pd.read_csv(fname)\n",
    "\n",
    "    cols = df.columns\n",
    "\n",
    "    df.head()\n",
    "\n",
    "    q = Query.objects.get(pk=1558)\n",
    "\n",
    "    docs = Doc.objects.filter(query=q)\n",
    "\n",
    "\n",
    "    # In[28]:\n",
    "\n",
    "    p = Project.objects.get(title=\"NETs\")\n",
    "    techs = Technology.objects.filter(project = p).values_list('name',flat=True)\n",
    "\n",
    "    ndf = df\n",
    "\n",
    "    def istech(x,t):\n",
    "        doi = str(x['url']).replace('http://dx.doi.org/','').strip()\n",
    "\n",
    "        soup = BeautifulSoup(x['description'])\n",
    "        rows = soup.find_all('tr')\n",
    "        arow = [r for r in rows if r.find_all(text=re.compile('Authors'))]\n",
    "        trow = [r for r in rows if r.find_all(text=re.compile('Title'))]\n",
    "        a = x['label'].split()[0]\n",
    "        \n",
    "        try:\n",
    "            title = trow[0].find_all('td')[1].text\n",
    "        except:\n",
    "            title = None\n",
    "\n",
    "        try:\n",
    "            doc = docs.get(\n",
    "                    wosarticle__di=doi\n",
    "                )\n",
    "        except:\n",
    "            try:\n",
    "                doc = docs.get(\n",
    "                    title__icontains=title\n",
    "                )\n",
    "            except:\n",
    "                try:\n",
    "                    py = x['label'].split()[1].replace('(','').replace(')','')\n",
    "                    doc = docs.get(\n",
    "                        docauthinst__AU__icontains=a,\n",
    "                        PY=py\n",
    "                    )\n",
    "                except:\n",
    "                    try:\n",
    "                        doc = docs.get(\n",
    "                            docauthinst__AU__icontains=a\n",
    "                        )\n",
    "                    except:\n",
    "                        return(np.nan)\n",
    "\n",
    "        if doc.technology.name==t:\n",
    "            return(1)\n",
    "        elif DocOwnership.objects.filter(\n",
    "                doc=doc,\n",
    "                query__technology__name=t,\n",
    "                relevant=1\n",
    "            ).count() > 0:\n",
    "            return(1)\n",
    "        else:\n",
    "            return(0)\n",
    "\n",
    "    #for t in techs:\n",
    "    for t in ['BECCS']:\n",
    "        ndf[t] = ndf.apply(lambda x: istech(x,t),axis=1)\n",
    "\n",
    "    ndf.head()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.4.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
